spring.application.name=discovery-server
server.port=8761

# Eureka Server config
server.servlet.context-path=/
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=true
eureka.server.eviction-interval-timer-in-ms=60000

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.observations.key-values.application=discovery-server
management.tracing.sampling.probability=1.0

