/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ankitshiksharthi.microserviceproject.payment_service.event;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PaymentFailedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7202748195793573821L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PaymentFailedEvent\",\"namespace\":\"com.ankitshiksharthi.microserviceproject.payment_service.event\",\"fields\":[{\"name\":\"paymentId\",\"type\":\"string\"},{\"name\":\"orderId\",\"type\":\"string\"},{\"name\":\"orderNumber\",\"type\":\"string\"},{\"name\":\"amount\",\"type\":\"double\"},{\"name\":\"paymentMethod\",\"type\":\"string\"},{\"name\":\"failureReason\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PaymentFailedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PaymentFailedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PaymentFailedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PaymentFailedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PaymentFailedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PaymentFailedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PaymentFailedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PaymentFailedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PaymentFailedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence paymentId;
  private java.lang.CharSequence orderId;
  private java.lang.CharSequence orderNumber;
  private double amount;
  private java.lang.CharSequence paymentMethod;
  private java.lang.CharSequence failureReason;
  private long timestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PaymentFailedEvent() {}

  /**
   * All-args constructor.
   * @param paymentId The new value for paymentId
   * @param orderId The new value for orderId
   * @param orderNumber The new value for orderNumber
   * @param amount The new value for amount
   * @param paymentMethod The new value for paymentMethod
   * @param failureReason The new value for failureReason
   * @param timestamp The new value for timestamp
   */
  public PaymentFailedEvent(java.lang.CharSequence paymentId, java.lang.CharSequence orderId, java.lang.CharSequence orderNumber, java.lang.Double amount, java.lang.CharSequence paymentMethod, java.lang.CharSequence failureReason, java.lang.Long timestamp) {
    this.paymentId = paymentId;
    this.orderId = orderId;
    this.orderNumber = orderNumber;
    this.amount = amount;
    this.paymentMethod = paymentMethod;
    this.failureReason = failureReason;
    this.timestamp = timestamp;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return paymentId;
    case 1: return orderId;
    case 2: return orderNumber;
    case 3: return amount;
    case 4: return paymentMethod;
    case 5: return failureReason;
    case 6: return timestamp;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: paymentId = (java.lang.CharSequence)value$; break;
    case 1: orderId = (java.lang.CharSequence)value$; break;
    case 2: orderNumber = (java.lang.CharSequence)value$; break;
    case 3: amount = (java.lang.Double)value$; break;
    case 4: paymentMethod = (java.lang.CharSequence)value$; break;
    case 5: failureReason = (java.lang.CharSequence)value$; break;
    case 6: timestamp = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'paymentId' field.
   * @return The value of the 'paymentId' field.
   */
  public java.lang.CharSequence getPaymentId() {
    return paymentId;
  }


  /**
   * Sets the value of the 'paymentId' field.
   * @param value the value to set.
   */
  public void setPaymentId(java.lang.CharSequence value) {
    this.paymentId = value;
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return The value of the 'orderId' field.
   */
  public java.lang.CharSequence getOrderId() {
    return orderId;
  }


  /**
   * Sets the value of the 'orderId' field.
   * @param value the value to set.
   */
  public void setOrderId(java.lang.CharSequence value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'orderNumber' field.
   * @return The value of the 'orderNumber' field.
   */
  public java.lang.CharSequence getOrderNumber() {
    return orderNumber;
  }


  /**
   * Sets the value of the 'orderNumber' field.
   * @param value the value to set.
   */
  public void setOrderNumber(java.lang.CharSequence value) {
    this.orderNumber = value;
  }

  /**
   * Gets the value of the 'amount' field.
   * @return The value of the 'amount' field.
   */
  public double getAmount() {
    return amount;
  }


  /**
   * Sets the value of the 'amount' field.
   * @param value the value to set.
   */
  public void setAmount(double value) {
    this.amount = value;
  }

  /**
   * Gets the value of the 'paymentMethod' field.
   * @return The value of the 'paymentMethod' field.
   */
  public java.lang.CharSequence getPaymentMethod() {
    return paymentMethod;
  }


  /**
   * Sets the value of the 'paymentMethod' field.
   * @param value the value to set.
   */
  public void setPaymentMethod(java.lang.CharSequence value) {
    this.paymentMethod = value;
  }

  /**
   * Gets the value of the 'failureReason' field.
   * @return The value of the 'failureReason' field.
   */
  public java.lang.CharSequence getFailureReason() {
    return failureReason;
  }


  /**
   * Sets the value of the 'failureReason' field.
   * @param value the value to set.
   */
  public void setFailureReason(java.lang.CharSequence value) {
    this.failureReason = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Creates a new PaymentFailedEvent RecordBuilder.
   * @return A new PaymentFailedEvent RecordBuilder
   */
  public static com.ankitshiksharthi.microserviceproject.payment_service.event.PaymentFailedEvent.Builder newBuilder() {
    return new com.ankitshiksharthi.microserviceproject.payment_service.event.PaymentFailedEvent.Builder();
  }

  /**
   * Creates a new PaymentFailedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PaymentFailedEvent RecordBuilder
   */
  public static com.ankitshiksharthi.microserviceproject.payment_service.event.PaymentFailedEvent.Builder newBuilder(com.ankitshiksharthi.microserviceproject.payment_service.event.PaymentFailedEvent.Builder other) {
    if (other == null) {
      return new com.ankitshiksharthi.microserviceproject.payment_service.event.PaymentFailedEvent.Builder();
    } else {
      return new com.ankitshiksharthi.microserviceproject.payment_service.event.PaymentFailedEvent.Builder(other);
    }
  }

  /**
   * Creates a new PaymentFailedEvent RecordBuilder by copying an existing PaymentFailedEvent instance.
   * @param other The existing instance to copy.
   * @return A new PaymentFailedEvent RecordBuilder
   */
  public static com.ankitshiksharthi.microserviceproject.payment_service.event.PaymentFailedEvent.Builder newBuilder(com.ankitshiksharthi.microserviceproject.payment_service.event.PaymentFailedEvent other) {
    if (other == null) {
      return new com.ankitshiksharthi.microserviceproject.payment_service.event.PaymentFailedEvent.Builder();
    } else {
      return new com.ankitshiksharthi.microserviceproject.payment_service.event.PaymentFailedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for PaymentFailedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PaymentFailedEvent>
    implements org.apache.avro.data.RecordBuilder<PaymentFailedEvent> {

    private java.lang.CharSequence paymentId;
    private java.lang.CharSequence orderId;
    private java.lang.CharSequence orderNumber;
    private double amount;
    private java.lang.CharSequence paymentMethod;
    private java.lang.CharSequence failureReason;
    private long timestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ankitshiksharthi.microserviceproject.payment_service.event.PaymentFailedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[0].schema(), other.paymentId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.orderId)) {
        this.orderId = data().deepCopy(fields()[1].schema(), other.orderId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.orderNumber)) {
        this.orderNumber = data().deepCopy(fields()[2].schema(), other.orderNumber);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.amount)) {
        this.amount = data().deepCopy(fields()[3].schema(), other.amount);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.paymentMethod)) {
        this.paymentMethod = data().deepCopy(fields()[4].schema(), other.paymentMethod);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.failureReason)) {
        this.failureReason = data().deepCopy(fields()[5].schema(), other.failureReason);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[6].schema(), other.timestamp);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing PaymentFailedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ankitshiksharthi.microserviceproject.payment_service.event.PaymentFailedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[0].schema(), other.paymentId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.orderId)) {
        this.orderId = data().deepCopy(fields()[1].schema(), other.orderId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.orderNumber)) {
        this.orderNumber = data().deepCopy(fields()[2].schema(), other.orderNumber);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.amount)) {
        this.amount = data().deepCopy(fields()[3].schema(), other.amount);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.paymentMethod)) {
        this.paymentMethod = data().deepCopy(fields()[4].schema(), other.paymentMethod);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.failureReason)) {
        this.failureReason = data().deepCopy(fields()[5].schema(), other.failureReason);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[6].schema(), other.timestamp);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'paymentId' field.
      * @return The value.
      */
    public java.lang.CharSequence getPaymentId() {
      return paymentId;
    }


    /**
      * Sets the value of the 'paymentId' field.
      * @param value The value of 'paymentId'.
      * @return This builder.
      */
    public com.ankitshiksharthi.microserviceproject.payment_service.event.PaymentFailedEvent.Builder setPaymentId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.paymentId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentId' field has been set.
      * @return True if the 'paymentId' field has been set, false otherwise.
      */
    public boolean hasPaymentId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'paymentId' field.
      * @return This builder.
      */
    public com.ankitshiksharthi.microserviceproject.payment_service.event.PaymentFailedEvent.Builder clearPaymentId() {
      paymentId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderId' field.
      * @return The value.
      */
    public java.lang.CharSequence getOrderId() {
      return orderId;
    }


    /**
      * Sets the value of the 'orderId' field.
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public com.ankitshiksharthi.microserviceproject.payment_service.event.PaymentFailedEvent.Builder setOrderId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.orderId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'orderId' field.
      * @return This builder.
      */
    public com.ankitshiksharthi.microserviceproject.payment_service.event.PaymentFailedEvent.Builder clearOrderId() {
      orderId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderNumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getOrderNumber() {
      return orderNumber;
    }


    /**
      * Sets the value of the 'orderNumber' field.
      * @param value The value of 'orderNumber'.
      * @return This builder.
      */
    public com.ankitshiksharthi.microserviceproject.payment_service.event.PaymentFailedEvent.Builder setOrderNumber(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.orderNumber = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'orderNumber' field has been set.
      * @return True if the 'orderNumber' field has been set, false otherwise.
      */
    public boolean hasOrderNumber() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'orderNumber' field.
      * @return This builder.
      */
    public com.ankitshiksharthi.microserviceproject.payment_service.event.PaymentFailedEvent.Builder clearOrderNumber() {
      orderNumber = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'amount' field.
      * @return The value.
      */
    public double getAmount() {
      return amount;
    }


    /**
      * Sets the value of the 'amount' field.
      * @param value The value of 'amount'.
      * @return This builder.
      */
    public com.ankitshiksharthi.microserviceproject.payment_service.event.PaymentFailedEvent.Builder setAmount(double value) {
      validate(fields()[3], value);
      this.amount = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'amount' field has been set.
      * @return True if the 'amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'amount' field.
      * @return This builder.
      */
    public com.ankitshiksharthi.microserviceproject.payment_service.event.PaymentFailedEvent.Builder clearAmount() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'paymentMethod' field.
      * @return The value.
      */
    public java.lang.CharSequence getPaymentMethod() {
      return paymentMethod;
    }


    /**
      * Sets the value of the 'paymentMethod' field.
      * @param value The value of 'paymentMethod'.
      * @return This builder.
      */
    public com.ankitshiksharthi.microserviceproject.payment_service.event.PaymentFailedEvent.Builder setPaymentMethod(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.paymentMethod = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentMethod' field has been set.
      * @return True if the 'paymentMethod' field has been set, false otherwise.
      */
    public boolean hasPaymentMethod() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'paymentMethod' field.
      * @return This builder.
      */
    public com.ankitshiksharthi.microserviceproject.payment_service.event.PaymentFailedEvent.Builder clearPaymentMethod() {
      paymentMethod = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'failureReason' field.
      * @return The value.
      */
    public java.lang.CharSequence getFailureReason() {
      return failureReason;
    }


    /**
      * Sets the value of the 'failureReason' field.
      * @param value The value of 'failureReason'.
      * @return This builder.
      */
    public com.ankitshiksharthi.microserviceproject.payment_service.event.PaymentFailedEvent.Builder setFailureReason(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.failureReason = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'failureReason' field has been set.
      * @return True if the 'failureReason' field has been set, false otherwise.
      */
    public boolean hasFailureReason() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'failureReason' field.
      * @return This builder.
      */
    public com.ankitshiksharthi.microserviceproject.payment_service.event.PaymentFailedEvent.Builder clearFailureReason() {
      failureReason = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.ankitshiksharthi.microserviceproject.payment_service.event.PaymentFailedEvent.Builder setTimestamp(long value) {
      validate(fields()[6], value);
      this.timestamp = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.ankitshiksharthi.microserviceproject.payment_service.event.PaymentFailedEvent.Builder clearTimestamp() {
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PaymentFailedEvent build() {
      try {
        PaymentFailedEvent record = new PaymentFailedEvent();
        record.paymentId = fieldSetFlags()[0] ? this.paymentId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.orderId = fieldSetFlags()[1] ? this.orderId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.orderNumber = fieldSetFlags()[2] ? this.orderNumber : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.amount = fieldSetFlags()[3] ? this.amount : (java.lang.Double) defaultValue(fields()[3]);
        record.paymentMethod = fieldSetFlags()[4] ? this.paymentMethod : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.failureReason = fieldSetFlags()[5] ? this.failureReason : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.timestamp = fieldSetFlags()[6] ? this.timestamp : (java.lang.Long) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PaymentFailedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<PaymentFailedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PaymentFailedEvent>
    READER$ = (org.apache.avro.io.DatumReader<PaymentFailedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.paymentId);

    out.writeString(this.orderId);

    out.writeString(this.orderNumber);

    out.writeDouble(this.amount);

    out.writeString(this.paymentMethod);

    out.writeString(this.failureReason);

    out.writeLong(this.timestamp);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.paymentId = in.readString(this.paymentId instanceof Utf8 ? (Utf8)this.paymentId : null);

      this.orderId = in.readString(this.orderId instanceof Utf8 ? (Utf8)this.orderId : null);

      this.orderNumber = in.readString(this.orderNumber instanceof Utf8 ? (Utf8)this.orderNumber : null);

      this.amount = in.readDouble();

      this.paymentMethod = in.readString(this.paymentMethod instanceof Utf8 ? (Utf8)this.paymentMethod : null);

      this.failureReason = in.readString(this.failureReason instanceof Utf8 ? (Utf8)this.failureReason : null);

      this.timestamp = in.readLong();

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.paymentId = in.readString(this.paymentId instanceof Utf8 ? (Utf8)this.paymentId : null);
          break;

        case 1:
          this.orderId = in.readString(this.orderId instanceof Utf8 ? (Utf8)this.orderId : null);
          break;

        case 2:
          this.orderNumber = in.readString(this.orderNumber instanceof Utf8 ? (Utf8)this.orderNumber : null);
          break;

        case 3:
          this.amount = in.readDouble();
          break;

        case 4:
          this.paymentMethod = in.readString(this.paymentMethod instanceof Utf8 ? (Utf8)this.paymentMethod : null);
          break;

        case 5:
          this.failureReason = in.readString(this.failureReason instanceof Utf8 ? (Utf8)this.failureReason : null);
          break;

        case 6:
          this.timestamp = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










